### PR TITLE
Added project details to readme

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Should each step of the pipeline refactoring project be elaborated?
* Add details about model organism data imported?
* Add breakdown of tasks involved in semantic similarity module?

**Comment by Shalsh23** [comment]
Resolves #6

**Comment by balhoff** [comment]
I think this is a good start, and it would be fine to go ahead and merge these updates. Additional enhancements could include some links, as Hilmar suggests, and also some information about requirements and instructions for running the Makefile.

**Comment by Shalsh23** [comment]
@hlapp I am not sure which links you mean. There seem to be no links in #6 .

**Comment by hlapp** [comment]
@Shalsh23 it looks like you found them and included them in #8.

**Pull request merged**
